#!/usr/bin/env python3
"""known_customers.py — FAIL-SAFE draft-time phone lookup for RETURNING PAID
customers (Step 2 pivot, 2026-06-07).

Replaces the dead "upsert clean profiles into customer_facts" approach: a box
dry-run proved customer_facts holds only the ~222 ACTIVE-lead rows, not the
1,383 all-time payers, so that path reached almost none of them. Instead we ship
a flat, self-contained lookup — known_customers.json, keyed by normalized phone
digits — that the draft path consults directly.

known_customers.json shape (generated by scripts/build_known_customers.py):
  { "<normalized-phone-digits>": {"name": str,
                                  "revenue_aed": <int|float|null>,
                                  "n_bookings": <int|null>}, ... }

CONTRACT:
  - load()  : reads known_customers.json ONCE (module-cached). A missing or
              broken file degrades to an empty dict — load() NEVER raises.
  - lookup(phone_or_cid) -> {name, revenue_aed, n_bookings} | None:
      * normalizes via the PROVEN hermes_exclusion_guards.normalize_phone
        (the single bridge normalizer — so the read-side key matches the key
        the builder wrote).
      * '<digits>@c.us'  -> the digits ARE the phone -> extract + normalize.
      * '<hash>@lid'     -> a privacy hash, NOT a phone -> None. We return None
        (graceful: NO recognition) rather than risk WRONG recognition.
      * empty / None / no-digits / a miss -> None.
      * Pure + fail-safe: never raises; returns a COPY so a caller can't mutate
        the module cache.

The data file sits next to this module and is loaded by absolute path
(Path(__file__).parent) — never cwd-relative.

PII: known_customers.json holds customer phone + revenue. It is .gitignored and
shipped to the box out of band (scp), not committed.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from hermes_exclusion_guards import normalize_phone

_DATA_PATH = Path(__file__).resolve().parent / "known_customers.json"

# Module cache. None = not yet loaded; a dict (possibly empty) once load() ran.
_CACHE: Optional[dict] = None


def _read(path) -> dict:
    """PURE: parse the JSON at `path` into a dict. Any failure — missing file,
    malformed JSON, or a non-dict top-level value — degrades to {}. Never
    raises (fail-safe: a broken data file must mean 'no recognition', never a
    crash on the draft path)."""
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:  # noqa: BLE001 — broken file -> empty, never raise
        return {}


def load() -> dict:
    """The lookup table, read from known_customers.json ONCE and cached. Returns
    a dict (empty on any load failure). Never raises."""
    global _CACHE
    if _CACHE is None:
        _CACHE = _read(_DATA_PATH)
    return _CACHE


def _identity_to_phone(identity) -> str:
    """Derive a phone string from any identity shape, mirroring
    hermes_exclusion_guards. '' when no phone is derivable (e.g. an @lid hash,
    which is NOT a phone). Tolerates non-string input by stringifying."""
    s = (identity if isinstance(identity, str) else "").strip()
    if not s:
        return ""
    if s.endswith("@lid"):
        # Privacy hash, not a phone. Without a (wrong-prone) resolver we return
        # no phone -> the caller gets None -> no recognition.
        return ""
    if s.endswith("@c.us"):
        return s.split("@", 1)[0]
    return s


def lookup(phone_or_cid) -> Optional[dict]:
    """Return {name, revenue_aed, n_bookings} for a known paid customer, or None.

    phone_or_cid may be a bare phone, a '+<digits>'/spaced phone, or a WhatsApp
    cid ('<digits>@c.us' / '<hash>@lid'). The phone is normalized with the proven
    bridge normalizer before lookup. An @lid (or any identity yielding no digits)
    returns None — graceful non-recognition beats wrong recognition. Never
    raises; returns a shallow COPY so the cache can't be mutated by the caller."""
    try:
        phone = _identity_to_phone(phone_or_cid)
        key = normalize_phone(phone)
        if not key:
            return None
        entry = load().get(key)
        return dict(entry) if isinstance(entry, dict) else None
    except Exception:  # noqa: BLE001 — must never break the draft path
        return None


def loaded_count() -> int:
    """Number of known-customer entries currently loaded (0 on load failure)."""
    return len(load())


if __name__ == "__main__":
    print(f"known_customers: {loaded_count()} entries loaded from {_DATA_PATH}")
